spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-ID, {@java.util.UUID.randomUUID()}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.wrapitup: DEBUG
    org.springframework.cloud.gateway: DEBUG